name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create zip file
        run: |
          cd custom_components/invader_tracker
          zip -r ../../invader_tracker.zip .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: invader_tracker.zip